spring.application.name=FirstAPI
spring.h2.console.enabled=true

spring.datasource.url=jdbc:h2:file:/Users/Prime/Documents/springboot/db
spring.datasource.username=kedarDB
spring.datasource.password=kedar123
spring.jpa.hibernate.ddl-auto=create
